"""empty message

Revision ID: 430d7140ff07
Revises: 
Create Date: 2024-05-15 12:30:32.732959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430d7140ff07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yo', sa.Float(precision=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('yo')

    # ### end Alembic commands ###
