"""empty message

Revision ID: 88e3c91712c0
Revises: 430d7140ff07
Create Date: 2024-05-15 16:32:56.210862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88e3c91712c0'
down_revision = '430d7140ff07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('yo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yo', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
